### ISSUE TITLE
Cannot run site locally

### ISSUE THREAD

**Issue by geoknee** [magmo/magmo.com#13]
```shell
(base) ➜  magmo.com git:(master) bundle install
/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /Users/georgeknee/magmo/magmo.com/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
	from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
(base) ➜  magmo.com git:(master) bundle update --bundler
Fetching https://github.com/middleman/middleman.git
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    middleman was resolved to 4.2.1, which depends on
      middleman-core (= 4.2.1) was resolved to 4.2.1, which depends on
        bundler (~> 1.1)

  Current Bundler version:
    bundler (2.2.3)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.1)', which is required by gem 'middleman-core (= 4.2.1)', in any of the sources.

Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    middleman was resolved to 4.2.1, which depends on
      middleman-core (= 4.2.1)

    middleman-autoprefixer (~> 2.7) was resolved to 2.9.0, which depends on
      middleman-core (>= 3.3.3)

    middleman-blog (~> 4.0.2) was resolved to 4.0.2, which depends on
      middleman-core (~> 4.0)

    middleman-google-analytics (~> 3.0.0) was resolved to 3.0.0, which depends on
      middleman-core (>= 3.4)

    middleman-syntax (~> 3.0.0) was resolved to 3.0.0, which depends on
      middleman-core (>= 3.2)
```

then 
```shell
bundle install         
/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /Users/georgeknee/magmo/magmo.com/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
	from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
(base) ➜  magmo.com git:(master) bundle update --bundler
Fetching https://github.com/middleman/middleman.git
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    middleman-blog (~> 4.0.2) was resolved to 4.0.2, which depends on
      middleman-core (~> 4.0) was resolved to 4.2.1, which depends on
        bundler (~> 1.1)

  Current Bundler version:
    bundler (2.2.30)

Your bundle requires a different version of Bundler than the one you're running.
Install the necessary version with `gem install bundler:1.17.3` and rerun bundler using `bundle _1.17.3_ update
--bundler`
(base) ➜  magmo.com git:(master) gem install bundler:1.17.3
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 2 seconds
1 gem installed

```
then 
```shell
 bundle _1.17.3_ update
--bundler
// snip
bundle install
// seems ok
```

```shell
(base) ➜  magmo.com git:(master) ✗ bundle exec middleman
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
Deprecation warning: Expected string default value for '--instrument'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
bundler: failed to load command: middleman (/Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bin/middleman)
NoMethodError: undefined method `decode' for URI:Module
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/util/paths.rb:36:in `normalize_path'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/sitemap/extensions/ignores.rb:21:in `ignore'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/extension.rb:554:in `call'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/extension.rb:554:in `proxy_method_call'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/extension.rb:504:in `block (2 levels) in initialize'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/middleman-blog-4.0.3/lib/middleman-blog/extension.rb:110:in `after_configuration'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/extension.rb:406:in `block in bind_after_configuration'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/callback_manager.rb:57:in `execute'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-core/lib/middleman-core/application.rb:306:in `initialize'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-cli/bin/middleman:49:in `new'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bundler/gems/middleman-12eb9ab3a960/middleman-cli/bin/middleman:49:in `<top (required)>'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bin/middleman:23:in `load'
  /Users/georgeknee/magmo/magmo.com/vendor/bundle/ruby/3.0.0/bin/middleman:23:in `<top (required)>'
```

**Comment by geoknee** [comment]
via #16
